// Represents a unique selling point for a company
export interface UniqueSellingPoint {
  feature: string;        // Feature description from form
  importance: number;     // Importance rating (1-5 scale)
  weight?: number;        // Optional calculated weight (derived from importance)
}

// Represents the company/profile information for a user
export interface UserDetails {
  companyId: string;      // Company identifier (from user.username)
  companyName: string;    // Company name
  industry: string;       // Industry category
  niche: string;          // Specific niche within industry
  location: string;       // Geographic location
  targetAudience: string; // Target audience description
  uniqueSellingPoints: UniqueSellingPoint[]; // Array of USPs
  captionTone: string;    // Preferred tone for captions
  captionFormatting: string; // Preferred formatting style
  brandAssociation: string;  // Brand association information
  promptTemplate?: string;   // Generated by backend based on other fields
}